-- Baseline: representa o schema atual, gerado historicamente por spring.jpa.hibernate.ddl-auto=update.
-- Em bancos de dev já existentes (não vazios, sem flyway_schema_history), o Flyway trata esta versão como
-- baseline (spring.flyway.baseline-on-migrate=true) e NÃO a executa. Em bancos vazios (ex.: H2 de teste),
-- este script roda normalmente e cria o schema do zero.

CREATE TABLE dim_cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    idade INTEGER,
    cidade VARCHAR(255),
    tipo_cliente VARCHAR(255),
    email VARCHAR(255),
    senha VARCHAR(255)
);

CREATE TABLE dim_prestador (
    id_prestador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    especialidade VARCHAR(255),
    nota_media NUMERIC(19,2),
    cidade VARCHAR(255)
);

CREATE TABLE dim_tempo (
    id_tempo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE,
    dia INTEGER,
    mes INTEGER,
    ano INTEGER,
    dia_semana VARCHAR(255)
);

CREATE TABLE dim_localizacao (
    id_localizacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cidade VARCHAR(255),
    estado VARCHAR(255),
    bairro VARCHAR(255)
);

CREATE TABLE fato_servicos (
    id_servico BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT REFERENCES dim_cliente(id_cliente),
    id_prestador BIGINT REFERENCES dim_prestador(id_prestador),
    id_tempo BIGINT REFERENCES dim_tempo(id_tempo),
    id_localizacao BIGINT REFERENCES dim_localizacao(id_localizacao),
    valor NUMERIC(19,2),
    tempo_execucao INTEGER,
    status VARCHAR(255),
    avaliacao INTEGER
);
