-- Nome de tabela foge de propósito do prefixo dim_/fato_: não é uma dimensão nem um fato,
-- é o catálogo de serviços publicados por um prestador (distinto da solicitação/transação em fato_servicos).
CREATE TABLE servico_ofertado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prestador BIGINT NOT NULL REFERENCES dim_prestador(id_prestador),
    categoria VARCHAR(120) NOT NULL,
    descricao VARCHAR(1000),
    preco NUMERIC(19,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ATIVO',
    id_localizacao BIGINT REFERENCES dim_localizacao(id_localizacao)
);

CREATE INDEX idx_servico_ofertado_categoria ON servico_ofertado(categoria);
CREATE INDEX idx_servico_ofertado_prestador ON servico_ofertado(id_prestador);
