CREATE TABLE pagamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fato_servico BIGINT NOT NULL UNIQUE REFERENCES fato_servicos(id_servico),
    valor_bruto NUMERIC(19,2) NOT NULL,
    valor_taxa NUMERIC(19,2) NOT NULL,
    valor_liquido NUMERIC(19,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    metodo_pagamento VARCHAR(60),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);

CREATE TABLE saque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prestador BIGINT NOT NULL REFERENCES dim_prestador(id_prestador),
    valor NUMERIC(19,2) NOT NULL,
    chave_pix_destino VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP NOT NULL
);

CREATE INDEX idx_saque_prestador ON saque(id_prestador);
