CREATE TABLE administrador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE parametro_negocio (
    chave VARCHAR(80) PRIMARY KEY,
    valor NUMERIC(19,4) NOT NULL,
    descricao VARCHAR(500)
);

-- RN01: taxa fixa abaixo do limiar, percentual a partir dele.
INSERT INTO parametro_negocio (chave, valor, descricao) VALUES
    ('taxa.limiar', 50.00, 'Valor do serviço acima do qual a taxa percentual passa a ser aplicada (RN01)'),
    ('taxa.fixa', 5.00, 'Taxa fixa cobrada para serviços com valor abaixo de taxa.limiar (RN01)'),
    ('taxa.percentual', 0.10, 'Percentual de taxa cobrado para serviços com valor >= taxa.limiar (RN01)'),
    ('solicitacao.prazo-resposta-horas', 24, 'Prazo máximo, em horas, para o prestador aceitar/recusar uma solicitação antes de expirar'),
    ('busca.raio-padrao-km', 10, 'Raio padrão, em km, usado na busca por geolocalização quando não informado');
