-- Painel do cliente: conta, endereços, favoritos, mensagens, código de confirmação
-- do atendimento (RN02) e taxa de cancelamento em favor do prestador (RN03).

-- ---------------------------------------------------------------------------
-- dim_cliente: dados de perfil que o cliente passa a poder manter, e a
-- unicidade de e-mail que dim_prestador tem desde V2 e esta tabela nunca teve.
-- Sem ela, duas contas com o mesmo e-mail fazem ClienteRepository.findByEmail
-- (que devolve Optional) estourar, e o login responde 500 em vez de 401.
-- Duplicados existentes precisam ser resolvidos ANTES desta migration.
-- ---------------------------------------------------------------------------
ALTER TABLE dim_cliente ADD COLUMN telefone VARCHAR(20);
ALTER TABLE dim_cliente ADD COLUMN foto_url VARCHAR(500);
ALTER TABLE dim_cliente ADD COLUMN ativo BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE dim_cliente ADD CONSTRAINT uk_dim_cliente_email UNIQUE (email);

-- ---------------------------------------------------------------------------
-- endereco_cliente: endereço de atendimento do cliente. Não substitui
-- dim_localizacao, que continua sendo a localização do serviço ofertado no
-- star schema — esta tabela tem rua, número e CEP, e pertence a um cliente.
-- Exclusão é lógica (ativo = FALSE): endereço já usado por uma solicitação
-- não pode desaparecer do histórico.
-- ---------------------------------------------------------------------------
CREATE TABLE endereco_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES dim_cliente(id_cliente),
    apelido VARCHAR(60) NOT NULL,
    cep VARCHAR(9) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(20) NOT NULL,
    complemento VARCHAR(120),
    bairro VARCHAR(120) NOT NULL,
    cidade VARCHAR(120) NOT NULL,
    uf VARCHAR(2) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    padrao BOOLEAN DEFAULT FALSE NOT NULL,
    ativo BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE INDEX idx_endereco_cliente_cliente ON endereco_cliente(id_cliente);

-- ---------------------------------------------------------------------------
-- favorito: prestadores que o cliente guardou. Um par cliente+prestador
-- existe no máximo uma vez.
-- ---------------------------------------------------------------------------
CREATE TABLE favorito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL REFERENCES dim_cliente(id_cliente),
    id_prestador BIGINT NOT NULL REFERENCES dim_prestador(id_prestador),
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT uk_favorito_cliente_prestador UNIQUE (id_cliente, id_prestador)
);

CREATE INDEX idx_favorito_cliente ON favorito(id_cliente);

-- ---------------------------------------------------------------------------
-- mensagem: conversa entre as duas partes de uma solicitação. O remetente é
-- identificado por papel + id porque cliente e prestador vivem em tabelas
-- diferentes, sem tabela de usuário unificada.
-- ---------------------------------------------------------------------------
CREATE TABLE mensagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fato_servico BIGINT NOT NULL REFERENCES fato_servicos(id_servico),
    remetente_tipo VARCHAR(20) NOT NULL,
    remetente_id BIGINT NOT NULL,
    conteudo VARCHAR(2000) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    lida_em TIMESTAMP
);

CREATE INDEX idx_mensagem_fato_servico ON mensagem(id_fato_servico);

-- ---------------------------------------------------------------------------
-- fato_servicos: código de confirmação do atendimento, endereço opcional e os
-- quatro momentos do ciclo. Antes disto a tabela não tinha nenhum timestamp —
-- só a dimensão dim_tempo, que é por dia e não sustenta uma linha de tempo.
-- Momento nulo significa "etapa não cumprida".
-- ---------------------------------------------------------------------------
ALTER TABLE fato_servicos ADD COLUMN pin_confirmacao VARCHAR(4);
ALTER TABLE fato_servicos ADD COLUMN id_endereco_cliente BIGINT REFERENCES endereco_cliente(id);
ALTER TABLE fato_servicos ADD COLUMN criado_em TIMESTAMP;
ALTER TABLE fato_servicos ADD COLUMN aceito_em TIMESTAMP;
ALTER TABLE fato_servicos ADD COLUMN iniciado_em TIMESTAMP;
ALTER TABLE fato_servicos ADD COLUMN concluido_em TIMESTAMP;

CREATE INDEX idx_fato_servicos_endereco_cliente ON fato_servicos(id_endereco_cliente);

-- ---------------------------------------------------------------------------
-- pagamento: estorno parcial. Guardar os dois valores é redundante em
-- aritmética e deliberado: registro financeiro se lê, não se recalcula.
-- ---------------------------------------------------------------------------
ALTER TABLE pagamento ADD COLUMN valor_estornado NUMERIC(19,2);
ALTER TABLE pagamento ADD COLUMN valor_taxa_cancelamento NUMERIC(19,2);

-- ---------------------------------------------------------------------------
-- RN03: taxa de cancelamento quando o cliente desiste de um atendimento já
-- iniciado. Vai integralmente para o prestador, que se deslocou; a plataforma
-- não retém nada nesse desfecho. Percentual maior quanto maior a distância.
-- ---------------------------------------------------------------------------
INSERT INTO parametro_negocio (chave, valor, descricao) VALUES
    ('cancelamento.carencia-minutos', 2, 'Minutos após o início do atendimento durante os quais o cliente ainda cancela com estorno integral (RN03)'),
    ('cancelamento.taxa-percentual-perto', 0.15, 'Percentual retido para o prestador quando a distância está dentro de cancelamento.limiar-distancia-km, ou quando não é apurável (RN03)'),
    ('cancelamento.taxa-percentual-longe', 0.20, 'Percentual retido para o prestador quando a distância ultrapassa cancelamento.limiar-distancia-km (RN03)'),
    ('cancelamento.limiar-distancia-km', 10, 'Distância, em km, que separa o percentual menor do maior na taxa de cancelamento (RN03)'),
    ('cancelamento.taxa-teto', 50.00, 'Teto absoluto, em reais, da taxa de cancelamento retida para o prestador (RN03)');
